#to copy currently selected parts from assembly with global placement
#with renaming to simplify names
sel = FreeCADGui.Selection.getSelection()
newObjs = []
for i,obj in enumerate(sel):
    print(obj.Label)
    newObjs.append(App.ActiveDocument.copyObject(obj))
    newObjs[-1].Placement = obj.getGlobalPlacement()
    newObjs[-1].Label = 'T{:03d}'.format(i)
    print(newObjs[-1].Label)

#write stp file for an assembly, preserving global position for each part
#and renaming to simplify PFC file
allObjs = []
file = '/home/tom/SPARC/CAD/test.stp'
count = 0
for obj in FreeCAD.ActiveDocument.Objects:
    if type(obj) == Part.Feature:
        tmpObj = App.ActiveDocument.copyObject(obj)
        tmpObj.Label = 'T{:03d}'.format(count)
        tmpObj.Placement = obj.getGlobalPlacement()
        allObjs.append(obj)
        count += 1

ImportGui.export(allObjs, file)

#append labels for a PFC intersect line that can be copied / pasted from python console
#before running, select the intersect parts in FreeCAD GUI
sel = FreeCADGui.Selection.getSelection()
line = ''
for obj in sel:
    print(obj.Label)
    line += ':'+obj.Label


print(line)


#hide objects by color.  Before running, select all objects to be included
#in GUI.  define the color first
color = (0.800000011920929, 1.0, 0.6000000238418579, 0.0)
sel = FreeCADGui.Selection.getSelection()
for obj in sel:
   if obj.ViewObject.ShapeColor == color:
      obj.ViewObject.Visibility = False
      #to delete, uncomment this line:
      #FreeCAD.ActiveDocument.removeObject(obj.Name)




#to move (translate) in direction normal to face.
#1st, select face for normal and send part to python console via right click in tree view
#then run (where delta = distance to move)
N = elt.normalAt(0,0)
delta = 10.0
move = delta*N #use negative for direction opposite normal
obj.Placement.move(move)